server:
  port: 8081
  servlet:
    context-path: /smg
# ƒ£∞Â≈‰÷√
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    check-template-location: true
